### ISSUE TITLE
Accepting `baseDir` in plugin config

### ISSUE THREAD

**Issue by ivstas** [FormidableLabs/babel-plugin-transform-define#36]
There is a common behaviour for many webpack plugins to require user specify `baseDir` in config instead of implicitly resolving path relatively to process.cwd.

Would you mind adding `baseDir` option to plugin config?

**Comment by ryan-roemer** [comment]
Closing as we've removed plugin config path from  `babel-plugin-transform-define@2.0.0` (everything dynamic should be able to be accomplished in babel7 with `.babelrc.js` and `babel.config.js` files).
