### ISSUE TITLE
Deprecate it

### ISSUE THREAD

**Issue by steida** [FormidableLabs/babel-plugin-transform-define#44]
I suppose this is a way to go https://github.com/zeit/next.js/tree/canary/examples/with-dotenv

**Comment by steida** [comment]
The reason is, having things in json file is risky and confusing.

**Comment by smeijer** [comment]
Bad idea, they serve different purposes. A version number should be embedded upon build, while api-keys, for example, should come from `ENV` keys.

`transform-define` and `dotenv` can and should live next to each other.
